### ISSUE TITLE
Questions regarding the use

### ISSUE THREAD

**Issue by ThomasTJdev** [olliNiinivaara/Suber#1]
Hi @olliNiinivaara 

This is a really cool repo. I found it through the Nim monthly journal - cadeau for adding it ;)

I have looked at the code base and the docs and I have 2 questions:
* Have you developed it with any specific usecase(s) in mind?
* Why use `Suber` instead of e.g. MQTT, websockets?

Thanks.

**Comment by olliNiinivaara** [comment]
Not directly comparable, because MQTT and websockets are protocol specifications whereas Suber implements a data structure.

You can definitely use Suber with websockets, and it's indeed the specific usecase in mind: Suber acting as the broker/hub that routes websocket messages between clients.

MQTT and similar protocols are designed for distributed systems ("SOAs") where messages may flow through multiple brokers using various paths, middlemen may be occasionally down, sender must get an ACK that message was delivered, etc etc.  Suber is designed for client-server architectures ("one web server, multiple browsers") and does not offer a way for client to detect that it missed a message (but when a websocket is reconnected, client can ask for messages since timestamp of last received message).

Distributed systems give rise to clusterf***ingly complex problems (think of Paxos, CAP theorem, Byzantine generals...) that are out of scope of Suber. Suber is motivated by the idea that if only we have (multithreading-friendly) data structures that smoothly scale out vertically, we may be able to avoid distribution...

**Comment by ThomasTJdev** [comment]
Thank you for the detailed reply @olliNiinivaara.

I will be testing Suber - it sounds like a match for me :).
